package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalItems implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "numberOfCars")
   private java.lang.Integer numberOfCars;
   @org.kie.api.definition.type.Label(value = "pool")
   private java.lang.Integer pool;
   @org.kie.api.definition.type.Label(value = "screenedEnclosureOverPool")
   private java.lang.Integer screenedEnclosureOverPool;

   public AdditionalItems()
   {
   }

   public java.lang.Integer getNumberOfCars()
   {
      return this.numberOfCars;
   }

   public void setNumberOfCars(java.lang.Integer numberOfCars)
   {
      this.numberOfCars = numberOfCars;
   }

   public java.lang.Integer getPool()
   {
      return this.pool;
   }

   public void setPool(java.lang.Integer pool)
   {
      this.pool = pool;
   }

   public java.lang.Integer getScreenedEnclosureOverPool()
   {
      return this.screenedEnclosureOverPool;
   }

   public void setScreenedEnclosureOverPool(
         java.lang.Integer screenedEnclosureOverPool)
   {
      this.screenedEnclosureOverPool = screenedEnclosureOverPool;
   }

   public AdditionalItems(java.lang.Integer numberOfCars,
         java.lang.Integer pool, java.lang.Integer screenedEnclosureOverPool)
   {
      this.numberOfCars = numberOfCars;
      this.pool = pool;
      this.screenedEnclosureOverPool = screenedEnclosureOverPool;
   }

}