package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DwellValue implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DwellValue() {
    }

}