package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DwellValue implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "dwellValue")
   private java.lang.Integer dwellValue;

   public DwellValue()
   {
   }

   public java.lang.Integer getDwellValue()
   {
      return this.dwellValue;
   }

   public void setDwellValue(java.lang.Integer dwellValue)
   {
      this.dwellValue = dwellValue;
   }

   public DwellValue(java.lang.Integer dwellValue)
   {
      this.dwellValue = dwellValue;
   }

}