package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HouseArea implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "squareFeet")
   private java.lang.Integer squareFeet;

   public HouseArea()
   {
   }

   public java.lang.Integer getSquareFeet()
   {
      return this.squareFeet;
   }

   public void setSquareFeet(java.lang.Integer squareFeet)
   {
      this.squareFeet = squareFeet;
   }

   public HouseArea(java.lang.Integer squareFeet)
   {
      this.squareFeet = squareFeet;
   }

}