package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HouseAge implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "hage")
   private java.lang.Integer hage;

   public HouseAge()
   {
   }

   public java.lang.Integer getHage()
   {
      return this.hage;
   }

   public void setHage(java.lang.Integer hage)
   {
      this.hage = hage;
   }

   public HouseAge(java.lang.Integer hage)
   {
      this.hage = hage;
   }

}