package com.demo.brms.demoinsuranceproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "firstName")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "lastName")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "address")
   private java.lang.String address;
   @org.kie.api.definition.type.Label(value = "city")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "state")
   private java.lang.String state;
   @org.kie.api.definition.type.Label(value = "zipCode")
   private java.lang.Integer zipCode;

   public Person()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Integer getZipCode()
   {
      return this.zipCode;
   }

   public void setZipCode(java.lang.Integer zipCode)
   {
      this.zipCode = zipCode;
   }

   public Person(java.lang.String firstName, java.lang.String lastName,
         java.lang.String address, java.lang.String city,
         java.lang.String state, java.lang.Integer zipCode)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
      this.city = city;
      this.state = state;
      this.zipCode = zipCode;
   }

}